name: E2E – Cypress

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cypress:
    runs-on: ubuntu-latest
    timeout-minutes: 45

    strategy:
      fail-fast: false
      matrix:
        platform: [DESKTOP, RESPONSIVE]

    env:
      # App + logging
      BASE_URL: https://www.saucedemo.com
      LOG_LEVEL: info
      # Platform picked from matrix and read by your config / LocatorClient
      PLATFORM: ${{ matrix.platform }}
      # Prevent CI from prompting
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Restore pnpm cache
        run: |
          pnpm store prune || true
          pnpm install --frozen-lockfile

      # (Optional) Show file tree for debugging
      - name: Show tree
        run: |
          echo "Matrix PLATFORM=${PLATFORM}"
          ls -la
          ls -la cypress || true
          ls -la cypress/e2e || true

      # Run Cypress. Your cypress.config.js will:
      #  - build registrars for tasks/validations
      #  - wire locator service tasks
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          headless: true
          # Keep default spec pattern from your config
          build: |
            echo "No build step"
          start: '' # no app server to start (we hit BASE_URL directly)
        env:
          BASE_URL: ${{ env.BASE_URL }}
          PLATFORM: ${{ matrix.platform }}
          LOG_LEVEL: ${{ env.LOG_LEVEL }}

      # Always upload artifacts for later inspection
      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: videos-${{ matrix.platform }}
          path: cypress/videos
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.platform }}
          path: cypress/screenshots
          if-no-files-found: ignore
          retention-days: 7